// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: contacts.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addcontact = `-- name: Addcontact :one
INSERT INTO contacts(id, username, room_id ,connected_on) VALUES ($1,$2,$3,$4)
RETURNING username, connected_on
`

type AddcontactParams struct {
	ID          uuid.UUID
	Username    string
	RoomID      uuid.UUID
	ConnectedOn time.Time
}

type AddcontactRow struct {
	Username    string
	ConnectedOn time.Time
}

func (q *Queries) Addcontact(ctx context.Context, arg AddcontactParams) (AddcontactRow, error) {
	row := q.db.QueryRowContext(ctx, addcontact,
		arg.ID,
		arg.Username,
		arg.RoomID,
		arg.ConnectedOn,
	)
	var i AddcontactRow
	err := row.Scan(&i.Username, &i.ConnectedOn)
	return i, err
}
