// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Connection struct {
	RequestBy      string
	RequestTo      string
	ConnectionID   uuid.UUID
	CreatedAt      time.Time
	SentAttempts   sql.NullInt32
	StatusSent     string
	StatusAccepted bool
}

type Notification struct {
	RequestBy     string
	RequestTo     string
	RequestStatus string
	CreatedAt     time.Time
	SentAttempts  sql.NullInt32
	StatusSent    string
}
