// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: notification.sql

package database

import (
	"context"
	"database/sql"
)

const dequeNotifications = `-- name: DequeNotifications :many
SELECT request_init_by, request_to FROM notifications WHERE status_sent=FALSE AND sent_attempts<3 ORDER BY created_at DESC
`

type DequeNotificationsRow struct {
	RequestInitBy string
	RequestTo     string
}

func (q *Queries) DequeNotifications(ctx context.Context) ([]DequeNotificationsRow, error) {
	rows, err := q.db.QueryContext(ctx, dequeNotifications)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DequeNotificationsRow
	for rows.Next() {
		var i DequeNotificationsRow
		if err := rows.Scan(&i.RequestInitBy, &i.RequestTo); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const notificationSent = `-- name: NotificationSent :exec
UPDATE notifications
SET sent_attempts = sent_attempts +1 , status_sent=TRUE
WHERE request_init_by=$1 AND request_to=$2
`

type NotificationSentParams struct {
	RequestInitBy string
	RequestTo     string
}

func (q *Queries) NotificationSent(ctx context.Context, arg NotificationSentParams) error {
	_, err := q.db.ExecContext(ctx, notificationSent, arg.RequestInitBy, arg.RequestTo)
	return err
}

const notificationnotSent = `-- name: NotificationnotSent :one
UPDATE notifications
SET sent_attempts = sent_attempts +1 
WHERE request_init_by=$1 AND request_to=$2
RETURNING sent_attempts,status_sent
`

type NotificationnotSentParams struct {
	RequestInitBy string
	RequestTo     string
}

type NotificationnotSentRow struct {
	SentAttempts sql.NullInt32
	StatusSent   bool
}

func (q *Queries) NotificationnotSent(ctx context.Context, arg NotificationnotSentParams) (NotificationnotSentRow, error) {
	row := q.db.QueryRowContext(ctx, notificationnotSent, arg.RequestInitBy, arg.RequestTo)
	var i NotificationnotSentRow
	err := row.Scan(&i.SentAttempts, &i.StatusSent)
	return i, err
}
