// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: user.sql

package database

import (
	"context"
)

const getEmail = `-- name: GetEmail :one
SELECT email FROM users WHERE username=$1
`

func (q *Queries) GetEmail(ctx context.Context, username string) (string, error) {
	row := q.db.QueryRowContext(ctx, getEmail, username)
	var email string
	err := row.Scan(&email)
	return email, err
}
